spring:
  application:
    name: spring-boot-quickstart

endpoints:
  health:
    sensitive: false

server:
  port: 8080
  context-path: /
  tomcat:
    max-threads: 200
    min-spare-threads: 25
    uri-encoding: UTF-8

logging:
  path: /tmp/${artifactId}

db:
  jdbcUrl:  jdbc:mysql://${db.host}:3306/${db.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: ${db.username}
  password: ${db.password}
  initialSize:  5
  maxActive: 50
  maxWait: 5000
  maxIdle: 10
  minIdle: 5
  removeAbandoned: true
  removeAbandonedTimeout: 180
  timeBetweenEvictionRunsMillis: 30000
  minEvictableIdleTimeMillis: 1800000
  testWhileIdle: true
  testOnBorrow: false
  numTestsPerEvictionRun: 5